name: Deploy to EC2

on:
  push:
    branches: [ main ]
  # Adicione outros eventos conforme necessário, como pull_request, workflow_dispatch, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Adicione outros passos aqui se necessário, como testes ou builds

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "."
        target: "/var/www/html/Reservando/"
        # Adicione outras configurações conforme necessário
